comp: ex_compile.c
	gcc ex_compile.c -Wall -o comp `pkg-config --cflags --libs glib-2.0`

wordcount: word_count.c
	gcc word_count.c -Wall -o wordcount `pkg-config --cflags --libs glib-2.0`

words: words.c
	gcc words.c -Wall -o words
